title: "49thIT"
author: "49thIT"
description: "An Alaskan serial adventure in IT..."

# Use only local theme files you’ve vendored into the repo
theme: null

# Optional: nicer URLs and correct base path
permalink: /:title/
url: "https://49thit.github.io"
baseurl: ""

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
